#!/bin/sh
#ibtool --generate-stringsfile MainMenu.strings English.lproj/MainMenu.nib
#ibtool --strings-file MainMenu.strings --write French.lproj/MainMenu.nib English.lproj/MainMenu.nib
#ibtool --generate-stringsfile MainMenu.strings French.lproj/MainMenu.nib

ibtool --previous-file English.lproj/prevMainMenu.nib \
       --incremental-file ./French.lproj/prevMainMenu.nib \
       --localize-incremental \
       --write ./French.lproj/MainMenu.nib \
       --errors \
       English.lproj/MainMenu.nib
